#!/bin/bash

#PBS -N spk_clstr_llm
#PBS -l select=1:ncpus=1:ngpus=1:mem=32gb:gpu_mem=20gb:scratch_local=100gb
#PBS -l walltime=0:1:0
#PBS -o logs/stdout.log
#PBS -e logs/stderr.log

cd /storage/brno2/home/tomn/mcorec/mcorec-baseline

module add mambaforge
module add cuda/12.6

mamba activate ./venv

export HF_HOME=/storage/brno2/home/tomn/.hf

mkdir -p results

echo "Starting experiment with model: $MODEL"

python script/cluster_llm.py --model $MODEL
python script/eval_cluster.py \
	| grep "Average Conversation Clustering F1 score:" \
	| awk -F": " -v m="$MODEL" '{print m "," $2}' >> results/f1_scores.csv

echo "Experiment completed. Results saved to results/f1_scores.csv"
